---
micronaut:
    application:
        name: bar-tender2
    server:
        port: ${random.port}
---
kafka:
    bootstrap:
        servers: localhost:9092

---
bar:
    pack:
        minTableSize: 8
        maxTableSize: 40
        minPackSize: 2
        maxPackSize: 8
        minPrice: 1000
        maxPrice: 4000
        beerTypes: ["American Amber Ale", "American Amber Lager", "American Barley Wine", "American Black Ale", "American Brett", "American Brown Ale", "American Cream Ale", "American Imperial Porter", "American Imperial Red Ale", "American Imperial Stout", "American IPA", "American Lager", "American Pale Ale", "American Sour", "American Stout", "American-Style Wheat Wine Ale", "American Wheat", "Baltic-Style Porter", "Barrel-Aged Beer", "Belgian-Style Blonde Ale", "Belgian-Style Dubbel", "Belgian-Style Flanders", "Belgian-Style Fruit Lambic", "Belgian-Style Golden Strong Ale", "Belgian-Style Lambic/Gueuze", "Belgian-Style Pale Ale", "Belgian-Style Quadrupel", "Belgian-Style Saison", "Belgian-Style Tripel", "Belgian-Style Witbier", "Berliner-Style Weisse", "French-Style Biere de Garde", "Blonde Ale", "Bohemian-Style Pilsener", "British-Style Barley Wine Ale", "California Common", "Chocolate Beer", "Coffee Beer", "Contemporary Gose", "English-Style Bitter", "English-Style Brown Ale", "English-Style Brown Porter", "English-Style Mild", "English-Style IPA", "English-Style Oatmeal Stout", "English-Style Old Ale", "English-Style Pale Ale (ESB)", "English-Style Sweet Stout (Milk Stout)", "European-Style Export", "Fruit and Field Beer", "German-Style Bock", "German-Style Brown/Altbier", "German-Style Doppelbock", "German-Style Dunkel", "German-Style Dunkelweizen", "German-Style Hefeweizen", "German-Style Maibock", "German-Style Helles", "German-Style Kolsch", "German-Style Marzen / Oktoberfest", "German-Style Pilsner", "German-Style Schwarzbier", "German-Style Weizenbock", "Gluten-Free Beer", "Herb and Spice Beer", "Honey Beer", "Imperial India Pale Ale", "Irish-Style Dry Stout", "Irish-Style Red Beer", "New England IPA", "Pumpkin Beer", "Robust Porter", "Rye Beer", "Scotch Ale/Wee Heavy", "Scottish-Style Ale", "Session Beer", "Smoke Beer", "Smoke Porter", "Specialty Beer", "Vienna-Style Lager"]