---
micronaut:
    application:
        name: places-api
                
    server:
        port: 8086

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/places"

grails:
    mongodb:
        databaseName: places

eureka:
    client:
        registration:
            enabled: true
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"