---
micronaut:
    application:
        name: micronaut-gorm-places-api
                
    server:
        port: 8086

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/places"

grails:
    mongodb:
        databaseName: places