# Create Technical User for marketplace api resource
POST http://{{host}}/beer
Content-Type: application/json

{
  "name": "someone",
  "money": 1500
}

> {%
    client.test("Order some beer", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
 %}
###
